language: node_js
node_js:
  - "4.1"
before_script:
  - npm i coffee -g
  - npm i mocha -g
script:
  - npm run coffee
  - npm test
after_script:
  - ./node_modules/.bin/jscover lib lib-cov
  - JS_COV=1 ./node_modules/.bin/mocha test -R mocha-lcov-reporter | TRAVIS=1 COVERALLS_REPO_TOKEN=$COVERALS_TOKEN ./node_modules/.bin/coveralls
