language: node_js
node_js:
  - "4.1"
before_script:
  - npm i coffee -g
  - npm i mocha -g
script:
  - npm run coffee
  - npm test
after_script:
  - ./node_modules/.bin/jscover lib lib-cov
  - JSCOV=1 ./node_modules/.bin/mocha test -R mocha-lcov-reporter > coverage.lcov
  - ./node_modules/.bin/codecov --token=$CODECOV_TOKEN
